### ISSUE TITLE
Error in selection of last 'day' off the week.

### ISSUE THREAD

**Issue by avinashknagar** [ua-cron/angular#11]
Quartz cron seems to consider Sunday as 1 and Saturday as 7.

![image](https://github.com/ua-cron/angular/assets/33415747/d624d8b8-77ae-4614-8ea6-c1f82b3c9d07)

on the other hand, all other online decoders of cron consider Monday as 1 and Sunday as 7
![image](https://github.com/ua-cron/angular/assets/33415747/813682c4-6e4e-490e-a7d0-61abbc0fd286)

**Comment by BzenkoSergey** [comment]
@avinashknagar 
have tried to find any documentation regarding the quartz cron format and what i see:

https://www.netiq.com/documentation/cloud-manager-2-5/ncm-reference/data/bexyssf.html
Day of the Week: 1-7 OR SUN-SAT

https://flylib.com/books/en/2.65.1/the_cron_expression_format.html
Day of Week: 17 or SUN-SAT

https://productresources.collibra.com/docs/collibra/latest/Content/Cron/co_quartz-cron-syntax.htm
day of the week: 1-7 or SUN-SAT

http://www.quartz-scheduler.org/documentation/quartz-2.3.0/tutorials/crontrigger.html
Day of week: 1-7 or SUN-SAT

**Comment by BzenkoSergey** [comment]
found an issue in cronhub repository (online decoder you use)

https://github.com/cronhub/crontab/issues/6
