### ISSUE TITLE
"[localization]" can't work !

### ISSUE THREAD

**Issue by webliuxiang** [ua-cron/angular#12]
`import { Bs5QuartzCronComponent, CronLocalization } from '@sbzen/ng-cron';`

`<bs5-quartz-cron  (changed)="dateValue = $event"></bs5-quartz-cron>` can work;

`<bs5-quartz-cron [localization]="localization" (changed)="dateValue = $event"></bs5-quartz-cron>` 

`error NG8002: Can't bind to 'localization' since it isn't a known property of 'bs5-quartz-cron'.`

**Comment by BzenkoSergey** [comment]
@webliuxiang what version of angular and @sbzen/ng-cron you use?
