### ISSUE TITLE
Need Angular 17 support

### ISSUE THREAD

**Issue by awdorrin** [ua-cron/angular#13]
npm ERR! Could not resolve dependency:
  npm ERR! peer @angular/common@"^16.0.0" from @sbzen/ng-cron@16.0.0
  npm ERR! node_modules/@sbzen/ng-cron
  npm ERR!   @sbzen/ng-cron@"^16.0.0" from the root project

Appears to work without issue when I force it locally, but I can't get it to build on the pipelines.

Please and Thank You :-)

**Comment by BzenkoSergey** [comment]
@awdorrin just released version 17.0.0, try

**Comment by awdorrin** [comment]
Thank you!
