### ISSUE TITLE
Support for angular 18

### ISSUE THREAD

**Issue by IODav** [ua-cron/angular#15]
npm error While resolving: @sbzen/ng-cron@17.0.0
npm error Found: @angular/common@18.1.3
npm error node_modules/@angular/common
npm error   @angular/common@"^18.1.2" from the root project
npm error   peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.1.3
npm error   node_modules/@angular/cdk
npm error     @angular/cdk@"^18.1.2" from the root project
npm error   7 more (@angular/forms, @angular/google-maps, ...)
npm error
npm error Could not resolve dependency:
npm error peer @angular/common@"^17.0.0" from @sbzen/ng-cron@17.0.0
npm error node_modules/@sbzen/ng-cron
npm error   @sbzen/ng-cron@"^17.0.0" from the root project

Hello, are there any plans for angular 18 support?
Thank you very much

**Comment by BzenkoSergey** [comment]
@IODav new version 18.0.0 has been released, try
