### ISSUE TITLE
Seeing buttons not tabs

### ISSUE THREAD

**Issue by awdorrin** [ua-cron/angular#4]
I am using Angular 14.1.3 (core/cli/material) with bootstrap 4.6.2
I installed @sbzen/ng-cron v 2.0.2, and inserted using: <quartz-cron></quartz-cron>
Instead of seeing a view with tabs, I am seeing 6 buttons (Seconds, Minute,s Hours, Day, Month, Year)

This is with Chrome 104.0.5112.82 and Firefox 102.1.0esr

**Comment by awdorrin** [comment]
I found one of your stackblitz examples and discovered that in the index.html you have:
`<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">`

If I add this to the index.html in my test project, the tabs show up, along with additional style formatting.

What I need to figure out is how I do this with my app, which is using SCSS, without adding the stylesheet to the index.html file.
I'd rather include it as part of the angular build, or component, if possible.

**Comment by BzenkoSergey** [comment]
> I found one of your stackblitz examples and discovered that in the index.html you have: `<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">`
> 
> If I add this to the index.html in my test project, the tabs show up, along with additional style formatting.
> 
> What I need to figure out is how I do this with my app, which is using SCSS, without adding the stylesheet to the index.html file. I'd rather include it as part of the angular build, or component, if possible.

Can you show how you add bootstrap to your project?

**Comment by awdorrin** [comment]
After some trial and error, I now have this working in my application. Here are the steps I followed:
1. `npm install bootstrap --save`
2. Update Angular.json  `"architect" :{ "build": { "options" : {` section with the following:

``` 
"styles": [
  {
    "input": "./src/sass/material-theme.scss",
    "inject": true
  },
  "./node_modules/bootstrap/scss/bootstrap.scss",
  "src/sass/styles.scss"
],
"scripts": [
  "node_modules/bootstrap/dist/js/bootstrap.min.js"
],
```

After rebuilding, now the styling logic is available, and it displays very well!

**Comment by BzenkoSergey** [comment]
> After some trial and error, I now have this working in my application. Here are the steps I followed:
> 
> 1. `npm install bootstrap --save`
> 2. Update Angular.json  `"architect" :{ "build": { "options" : {` section with the following:
> 
> ```
> "styles": [
>   {
>     "input": "./src/sass/material-theme.scss",
>     "inject": true
>   },
>   "./node_modules/bootstrap/scss/bootstrap.scss",
>   "src/sass/styles.scss"
> ],
> "scripts": [
>   "node_modules/bootstrap/dist/js/bootstrap.min.js"
> ],
> ```
> 
> After rebuilding, now the styling logic is available, and it displays very well!

You can also use this approach https://getbootstrap.com/docs/4.6/getting-started/theming/

**Comment by awdorrin** [comment]
I will take a look at that as well, thank you!
