### ISSUE TITLE
Provide update for Angular 15

### ISSUE THREAD

**Issue by awdorrin** [ua-cron/angular#6]
Having an issue updating my project to Angular 15 due to this package being limited to angular "^14.1.0"
I'm thinking this should just be a package.json update to allow Angular 15.

**Comment by BzenkoSergey** [comment]
> Having an issue updating my project to Angular 15 due to this package being limited to angular "^14.1.0" I'm thinking this should just be a package.json update to allow Angular 15.

New version 15.0.0 has been released, try it.

**Comment by awdorrin** [comment]
Thanks!

**Comment by awdorrin** [comment]
Installed and tested, looks good. thanks again!
