### ISSUE TITLE
Support for angular 15+

### ISSUE THREAD

**Issue by awdorrin** [ua-cron/angular#8]
Since your project is dependent upon ng-bootstrap, I can't use the library in an Angular 15 application without forcing an install with 
--legacy-peer-deps
I'm wondering if you've considered implementing the css without ng-bootstrap?

**Comment by BzenkoSergey** [comment]
> Since your project is dependent upon ng-bootstrap, I can't use the library in an Angular 15 application without forcing an install with --legacy-peer-deps I'm wondering if you've considered implementing the css without ng-bootstrap?

I don't see any dependencies on ng-bootstrap. 
Please provide more details.

<img width="941" alt="image" src="https://user-images.githubusercontent.com/5772034/232250463-0b217d3c-26bf-41c1-8f36-35d8d9cea41b.png">

**Comment by BzenkoSergey** [comment]
Mb will help: https://ngcron.emptyui.com/doc/customization/css-styling#whole-redesign

**Comment by awdorrin** [comment]
Apologies for not responding to this sooner, the earlier notifications must have slipped past me.in email. Yes, I was mistaken regarding ng-bootstrap vs bootstrap due to other migration issues that we were encountering at the time. I should have come back to close/delete the post.
I will take the opportunity to thank you,  this component has worked very well for us in several situations, and really clears up confusion some of my coworkers have about cron syntax. :-)
