### ISSUE TITLE
Support for angular 16

### ISSUE THREAD

**Issue by ips219** [ua-cron/angular#9]
Are there plans for supporting Angular 16?

`
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^15.0.4" from @sbzen/ng-cron@15.0.0
npm ERR! node_modules/@sbzen/ng-cron
npm ERR!   @sbzen/ng-cron@"15.0.0" from the root project
`

**Comment by BzenkoSergey** [comment]
@ips219 
New version 16.0.0 has been released, try it.

**Comment by ips219** [comment]
It's working fine

![image](https://github.com/ua-cron/angular/assets/3368591/5ffe1c49-4d9b-483f-b44b-9196f7c002f8)

Thanks!
